name: MinesweeperCI

# Contains all the things to do after code is merged into master
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend/

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run tests
        run: npm test
          
  frontend:
    name: Backend CI
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend/

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint

      - name: Run tests
        run: npm test